# Test FastAPI endpoints
# Replace the API key below with your actual key from .env file

@api_key = API_KEY

###
# API health check
GET http://127.0.0.1:8000/
Accept: application/json

###
# List all available ollama models
GET http://127.0.0.1:8000/list
Accept: application/json
X-API-Key: {{api_key}}

###
# Simple Chat
POST http://127.0.0.1:8000/chat
Content-Type: application/json
X-API-Key: {{api_key}}

{
  "model": "llama3.2:3b-instruct-q4_K_M",
  "prompt": "What is 2+3?"
}

###

# Test chat with conversation history
POST http://127.0.0.1:8000/chat
Content-Type: application/json
X-API-Key: {{api_key}}

{
  "model": "llama3.2:3b-instruct-q4_K_M",
  "prompt": "What about Paris?",
  "history": [
    {
      "role": "user",
      "content": "What's the weather in London?"
    },
    {
      "role": "assistant",
      "content": "The Weather today in London is 14 degrees Celsius."
    }
  ]
}

###

# Test Complex query
POST http://127.0.0.1:8000/chat
Content-Type: application/json
X-API-Key: {{api_key}}

{
  "model": "llama3.2:3b-instruct-q4_K_M",
  "prompt": "Find the current weather in the capital of the country where the Eiffel Tower is located."
}

###

# Test automatic search with Wikipedia
POST http://127.0.0.1:8000/chat
Content-Type: application/json
X-API-Key: {{api_key}}

{
  "model": "llama3.2:3b-instruct-q4_K_M",
  "prompt": "Who won the 2025 presidential election in poland?"
}

###

# Test opinions search on reddit with stream response
POST http://127.0.0.1:8000/chat/stream
Content-Type: application/json
X-API-Key: {{api_key}}

{
  "model": "llama3.2:3b-instruct-q4_K_M",
  "prompt": "what are people saying about OLED gaming monitors recently?"
}

###
# Test 2-Call Flow
POST http://127.0.0.1:8000/chat
Content-Type: application/json
X-API-Key: {{api_key}}

{
  "model": "llama3.2:3b-instruct-q4_K_M",
  "prompt": "What advancements have been made in quantum physics over the past 6 months?",
  "history": []
}

###

# Test with user memory context
POST http://127.0.0.1:8000/chat
Content-Type: application/json
X-API-Key: {{api_key}}

{
  "model": "llama3.2:3b-instruct-q4_K_M",
  "prompt": "Recommend me a good restaurant for tonight",
  "user_memory": "I live in Boston. I have a nut allergy. I don't like to go out on rain."
}

###

# Test RECALL functionality - Step 1: Perform a search to get a search_id
POST http://127.0.0.1:8000/chat
Content-Type: application/json
X-API-Key: {{api_key}}

{
  "model": "llama3.2:3b-instruct-q4_K_M",
  "prompt": "What's on the news about Cloudflare outage?"
}

###

# Test RECALL functionality - Step 2: keep search_id in history as reference
# Replace with actual search_id
POST http://127.0.0.1:8000/chat/stream
Content-Type: application/json
X-API-Key: {{api_key}}

{
  "model": "gemma3:4b-it-qat",
  "prompt": "did the source mention anything else?",
  "history": [
    {
      "role": "user",
      "content": "What's on the news about Cloudflare outage?"
    },
    {
      "role": "assistant",
      "content": "There's been a big deal in the tech world lately - Cloudflare had a massive outage that affected millions of websites and services across the internet. It happened on November 18, 2025, and started causing error messages to flash up on websites around 11:48 am London time.",
      "search_id": 18
    }
  ]
}

###